### PR TITLE
Use C99 in CI

### PR DESCRIPTION
**Pull request by dangitall**
Is this the right way to do this?

### CODE REVIEW

**Comment by jonm** [comment]
Yes, that's the right way to update the flags for CI; looks like we just have to fix the ensuing non-C99-standard warnings.

**Comment by jonm** [comment]
Hmm, those are odd errors in the CI build; complaining about missing function prototypes but the `#include` of system files are definitely there. According to `man gcc`, C99 isn't fully supported by `gcc` yet, but must also be invoked with `-pedantic-errors -fextended-identifiers`:

https://gcc.gnu.org/c99status.html

However, that doesn't seem to let the build pass for me. I am up at the moment and will poke at this a bit and record what I find.

**Comment by jonm** [comment]
Ok, here's what I found when looking into the first error for a missing proto for `srandom`. On a local Vagrant Linux box, this proto is in `stdlib.h` but is surrounded by:

`#if defined __USE_SVID || defined __USE_XOPEN_EXTENDED || defined __USE_BSD`

These symbols seem to be set from `/usr/include/features.h`, where it looks like `__USE_BSD` gets set either if `-D_GNU_SOURCE` is defined by the user or if `__STRICT_ANSI__` and `_ISOC99_SOURCE` are _not_ defined. I wonder if adding `-std=c99` turns on the latter.

In any event, I was able to get the build to compile with:

`CFLAGS="-D_GNU_SOURCE -ansi -std=c99 -fextended-identifiers -Wall -Wextra -Werror"`

Random question: why do we want to use `-std=c99`? C programming is not my day job so I'm just curious.

**Comment by dangitall** [comment]
Ah ok. I knew (after gcc had jogged my memory!) that `srandom` wasn't strict c99 compliant, but what I didn't (still don't) know was why clang wasn't reporting this errors even with `-std=c99` enabled locally. 

I was going here because gcc was throwing warnings on variables initialized inside a for statement. I.e.:

```
for(int i=0; i < 10; i++)
```

The right way for us to do this for gcc is probably `-std=gnu99` which won't be such a stickler. I just didn't know immediately if this was going to be an issue for clang.

**Comment by dangitall** [comment]
Ok, I just bit the bullet and installed gcc-4.8 on my machine to get this working. Should be good now.

**Pull request merged**
