### PR TITLE
Send to charf

### PR DESCRIPTION
**Pull request by dangitall**
`send_to_charf`:`send_to_char`::`log_msgf`::`log_msg`

Plus, I like the saying 'send_to_charf` out loud.

### CODE REVIEW

**Comment by dangitall** [comment]
I don't know what's up with the duplication of all those commits. Sometimes git foils me. :cry:

**Comment by jonm** [comment]
By the way, you can do a lot of commit squashing and rearranging with `git rebase -i`. This article was very enlightening for me:
http://blog.plover.com/prog/git-habits.html

**Comment by dangitall** [comment]
:+1:

**Comment by jonm** [comment]
I am :+1: to this in concept, although I have not reviewed in detail, so you may merge or wait for my review as you desire.

**Comment by jonm** [comment]
And I'm really leaving now.

**Comment by jonm** [comment]
Needs rebased?

**Pull request merged**
